# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Erin Zaich
tagline:          'Progressive educator'
description:      'Progressive educator'
url:              http://erinzaich.com
baseurl:          /

author:
  name:           'Erin Zaich'
  url:            https://twitter.com/ebzaich

paginate:         5

# Custom vars
# version:          2.1.0
